DELETE FROM RATING;
INSERT INTO RATING (NAME)  VALUES ( 'G') ; --1
INSERT INTO RATING (NAME) VALUES ( 'PG'); --2
INSERT INTO RATING (NAME) VALUES ( 'PG-13'); --3
INSERT INTO RATING (NAME) VALUES ( 'R'); --4
INSERT INTO RATING (NAME) VALUES ( 'NC-17'); --5
DELETE FROM GENRE;
INSERT INTO GENRE (NAME) VALUES ( 'Комедия'); --1
INSERT INTO GENRE (NAME) VALUES ( 'Драма'); --2
INSERT INTO GENRE (NAME) VALUES ( 'Мультфильм'); --3
INSERT INTO GENRE (NAME) VALUES ( 'Триллер'); --4
INSERT INTO GENRE (NAME) VALUES ( 'Документальный'); --5
INSERT INTO GENRE (NAME) VALUES ( 'Боевик'); --6